name: deploy
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true -Denv=staging -f pom.xml
      - name: Save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-bundle
          path: ./target/bookshelf-service-0.0.1-SNAPSHOT.jar
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Download jar artifact
        uses: actions/download-artifact@v2
        with:
          name: build-bundle
      - name: Install aws cli and deploy
        run: pip install awscli
      - run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      - run: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: aws configure set region eu-west-3
      - run: aws s3 cp bookshelf-service-0.0.1-SNAPSHOT.jar s3://elasticbeanstalk-eu-west-3-317065409374/bookshelf-service-$GITHUB_RUN_ID.jar
      - run: aws elasticbeanstalk create-application-version --application-name bookshelf-service --version-label bookshelf-service-staging-$GITHUB_RUN_ID --source-bundle S3Bucket=elasticbeanstalk-eu-west-3-317065409374,S3Key=bookshelf-service-$GITHUB_RUN_ID.jar
      - run: aws elasticbeanstalk update-environment --application-name bookshelf-service --environment-name BookshelfService-env --version-label bookshelf-service-staging-$GITHUB_RUN_ID
